ci: refactor GitHub Actions workflow notification logic

diff --git a/.github/workflows/continuous-delivery.yml b/.github/workflows/continuous-delivery.yml
--- a/.github/workflows/continuous-delivery.yml
+++ b/.github/workflows/continuous-delivery.yml
@@ -7,13 +7,13 @@ concurrency:
 on:
   push:
     branches:
-      - 'prod'
-      - 'dev'
+      - "prod"
+      - "dev"
 
   pull_request:
     branches:
-      - '**'
-      - '!prod'
+      - "**"
+      - "!prod"
     types:
       - opened
       - synchronize
@@ -23,7 +23,8 @@ on:
 
 env:
   BRANCH_NAME: ${{ github.ref_name }}
-  PROD_URL: 'https://www.daoedu.tw/'
+  IS_INTERNAL_PR: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
+  PROD_URL: "https://www.daoedu.tw/"
   HUSKY: 0
 
 jobs:
@@ -57,6 +58,7 @@ jobs:
         run: yarn install --frozen-lockfile
 
       - name: Build
+        id: build
         run: yarn pages:build
         env:
           NEXT_PUBLIC_API_URL: ${{ github.ref_name == 'prod' && secrets.NEXT_PUBLIC_API_URL || secrets.NEXT_PUBLIC_API_URL_DEV }}
@@ -73,36 +75,29 @@ jobs:
           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
           command: pages deploy --branch=${{ env.BRANCH_NAME }}
 
-    outputs:
-      preview-url: ${{ github.ref_name == 'prod' && env.PROD_URL || steps.deploy.outputs.pages-deployment-alias-url }}
-      cmd-output: ${{ steps.deploy.outputs.command-stderr }}
-
-  send_result:
-    name: Send Result
-    runs-on: ubuntu-latest
-    needs: build_and_deploy
-    env:
-      HAS_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL != '' }}
-    if: always()
-
-    steps:
-      - name: Git checkout
-        uses: actions/checkout@v4
-
       - name: Send Build and Deploy Failed Notification
-        if: ${{ needs.build_and_deploy.result == 'failure' && env.HAS_WEBHOOK == 'true' }}
+        if: (steps.build.outcome == 'false' || steps.deploy.outcome == 'failure') && env.IS_INTERNAL_PR == 'true'
         uses: ./.github/actions/notification
         with:
           TYPE: failure
-          TITLE: '❌ Build and Deploy Failed'
-          DESCRIPTION: '${{ needs.build_and_deploy.outputs.cmd-output }}'
+          TITLE: "❌ Build and Deploy Failed"
+          DESCRIPTION: "${{ steps.deploy.outputs.command-stderr }}"
           DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
 
+      - name: Check on failure
+        if: steps.build.outcome == 'false' || steps.deploy.outcome == 'failure'
+        env:
+          ERROR: ${{ steps.deploy.outputs.command-stderr }}
+        run: |
+          echo "❌ Build and Deploy Failed"
+          echo $ERROR
+          exit 1
+
       - name: Send Build Succeeded Notification
-        if: ${{ needs.build_and_deploy.result == 'success' && env.HAS_WEBHOOK == 'true' }}
+        if: steps.deploy.outcome == 'success' && env.IS_INTERNAL_PR == 'true'
         uses: ./.github/actions/notification
         with:
           TYPE: success
-          TITLE: '✅ Build Succeeded'
-          DESCRIPTION: 'Preview URL: ${{ needs.build_and_deploy.outputs.preview-url }}'
+          TITLE: "✅ Build Succeeded"
+          DESCRIPTION: "Preview URL: ${{ github.ref_name == 'prod' && env.PROD_URL || steps.deploy.outputs.pages-deployment-alias-url }}"
           DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
